### PR TITLE
Add .ahab support for Android

### LINKED ISSUE #11: Add .ahab support for Android
As stated in the readme.md, the support for .ahab files in Android is still missing. To support custom haptic behaviour based on .ahab files on all devices, a Android implementation should be provided as well.

I started on a Pull Request implementing .ahab support on Android. It still has some values that are missing based on the documentation of Apple. Also the only thing that is considered now is the Intensity of an event. The Sharpness is, as far as I know, not something that can be controlled with the vibration api of Android.

https://github.com/istornz/flutter_gaimon/pull/10

@istornz What do you think of the current approach? I intend to add the implementation of missing values as well

### PR DESCRIPTION
**Pull request by Bassiuz**
This is the start of supporting .ahab files for Android.

closes https://github.com/istornz/flutter_gaimon/issues/11
 
- [X] Parse .ahab json contents
- [X] Convert events in pattern to waveform
- [X] Send waveform to android native plugin to simulate waveform
- [x] Add support for parameters (https://developer.apple.com/documentation/corehaptics/representing-haptic-patterns-in-ahap-files)
- [x] Add support for Parameter curves
- [ ] Add support for AttackTime
- [ ] Add support for DecayTime
- [ ] Add support for Sustained Events

### CODE REVIEW

**Review by istornz — APPROVED** [review]
LGTM

**Comment by SuhwanCha** [comment]
@istornz Can it be merged and published? I'm looking forward it

**Comment by Bassiuz** [comment]
@SuhwanCha ; Cool that you are looking forward to it! I intend to finish up the last of these points next friday. Whenever that is finished I will convert it from a draft to an actual pr so we can merge it.

**Comment by istornz** [comment]
> @SuhwanCha ; Cool that you are looking forward to it! I intend to finish up the last of these points next friday. Whenever that is finished I will convert it from a draft to an actual pr so we can merge it.

Thanks @Bassiuz

**Comment by Bassiuz** [comment]
@istornz I added support for parameters and parameter curves. These curves are still linear instead of curved with attack/sustain and release, but for the first release I think that is acceptable.

The curves feel somewhat acceptable, however the difference in sharpness isn't feelable, as I didn't apply it to the amplitude of the waveform. So only if you have a .ahap that makes use of a lot of Intensity Curves or other intensity controls you will feel similair results.

Do you have a good idea to combine the sharpness into the waveform? Should I treat it as a certain multiplier? (improve the amplitude for very sharp haptics, lower it when the sharpness is very low?)

**Review by istornz — APPROVED** [review]

**Comment by istornz** [comment]
Hi @Bassiuz thanks for your awesome PR!
I think we can merge it right now & improve it in the future 👍 (I'm in vacation now I will check how to implement extra feature later).

What do you think?

Thanks for your work!

**Comment by Bassiuz** [comment]
@istornz Yeah lets just merge it for now and brainstorm on how to improve and expand later. 

Are you by any chance able to create a release?

Enjoy your vacation! 🏖️

**Comment by istornz** [comment]
@Bassiuz I will do a release next week I think 👍

Thanks 🙏

**Comment by istornz** [comment]
Release v1.3.0 is now live on pub.dev 👍

**Pull request merged**
